# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ruby - For Future Reference
email: brian@rubyffr.com
description: This is a blog which is about things that I learn about Ruby, Rails and web development.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rubyffr.com" # the base hostname & protocol for your site
twitter_username: becker1701
github_username:  becker1701

# Build settings
markdown: kramdown

gems: ['kramdown']
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', '_vendor', 'Procfile', 'Rakefile']